FROM jenkins/jenkins:lts

USER root

RUN apt-get update \
    && apt-get install -y docker.io python3-pip \
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --break-system-packages flask pytest

USER jenkins